
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.385+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "ClientCompteNotCloseException", targetNamespace = "http://front.server.bank.alom/")
public class ClientCompteNotCloseException_Exception extends Exception {

    private alom.bank.client.ClientCompteNotCloseException clientCompteNotCloseException;

    public ClientCompteNotCloseException_Exception() {
        super();
    }

    public ClientCompteNotCloseException_Exception(String message) {
        super(message);
    }

    public ClientCompteNotCloseException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClientCompteNotCloseException_Exception(String message, alom.bank.client.ClientCompteNotCloseException clientCompteNotCloseException) {
        super(message);
        this.clientCompteNotCloseException = clientCompteNotCloseException;
    }

    public ClientCompteNotCloseException_Exception(String message, alom.bank.client.ClientCompteNotCloseException clientCompteNotCloseException, java.lang.Throwable cause) {
        super(message, cause);
        this.clientCompteNotCloseException = clientCompteNotCloseException;
    }

    public alom.bank.client.ClientCompteNotCloseException getFaultInfo() {
        return this.clientCompteNotCloseException;
    }
}
