
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.366+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "ClientExistException", targetNamespace = "http://front.server.bank.alom/")
public class ClientExistException_Exception extends Exception {

    private alom.bank.client.ClientExistException clientExistException;

    public ClientExistException_Exception() {
        super();
    }

    public ClientExistException_Exception(String message) {
        super(message);
    }

    public ClientExistException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClientExistException_Exception(String message, alom.bank.client.ClientExistException clientExistException) {
        super(message);
        this.clientExistException = clientExistException;
    }

    public ClientExistException_Exception(String message, alom.bank.client.ClientExistException clientExistException, java.lang.Throwable cause) {
        super(message, cause);
        this.clientExistException = clientExistException;
    }

    public alom.bank.client.ClientExistException getFaultInfo() {
        return this.clientExistException;
    }
}
