
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.379+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "CompteTypeExistException", targetNamespace = "http://front.server.bank.alom/")
public class CompteTypeExistException_Exception extends Exception {

    private alom.bank.client.CompteTypeExistException compteTypeExistException;

    public CompteTypeExistException_Exception() {
        super();
    }

    public CompteTypeExistException_Exception(String message) {
        super(message);
    }

    public CompteTypeExistException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CompteTypeExistException_Exception(String message, alom.bank.client.CompteTypeExistException compteTypeExistException) {
        super(message);
        this.compteTypeExistException = compteTypeExistException;
    }

    public CompteTypeExistException_Exception(String message, alom.bank.client.CompteTypeExistException compteTypeExistException, java.lang.Throwable cause) {
        super(message, cause);
        this.compteTypeExistException = compteTypeExistException;
    }

    public alom.bank.client.CompteTypeExistException getFaultInfo() {
        return this.compteTypeExistException;
    }
}
