
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.340+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "CompteNotExistException", targetNamespace = "http://front.server.bank.alom/")
public class CompteNotExistException_Exception extends Exception {

    private alom.bank.client.CompteNotExistException compteNotExistException;

    public CompteNotExistException_Exception() {
        super();
    }

    public CompteNotExistException_Exception(String message) {
        super(message);
    }

    public CompteNotExistException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CompteNotExistException_Exception(String message, alom.bank.client.CompteNotExistException compteNotExistException) {
        super(message);
        this.compteNotExistException = compteNotExistException;
    }

    public CompteNotExistException_Exception(String message, alom.bank.client.CompteNotExistException compteNotExistException, java.lang.Throwable cause) {
        super(message, cause);
        this.compteNotExistException = compteNotExistException;
    }

    public alom.bank.client.CompteNotExistException getFaultInfo() {
        return this.compteNotExistException;
    }
}
