
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.373+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "CompteTypeNotExistException", targetNamespace = "http://front.server.bank.alom/")
public class CompteTypeNotExistException_Exception extends Exception {

    private alom.bank.client.CompteTypeNotExistException compteTypeNotExistException;

    public CompteTypeNotExistException_Exception() {
        super();
    }

    public CompteTypeNotExistException_Exception(String message) {
        super(message);
    }

    public CompteTypeNotExistException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CompteTypeNotExistException_Exception(String message, alom.bank.client.CompteTypeNotExistException compteTypeNotExistException) {
        super(message);
        this.compteTypeNotExistException = compteTypeNotExistException;
    }

    public CompteTypeNotExistException_Exception(String message, alom.bank.client.CompteTypeNotExistException compteTypeNotExistException, java.lang.Throwable cause) {
        super(message, cause);
        this.compteTypeNotExistException = compteTypeNotExistException;
    }

    public alom.bank.client.CompteTypeNotExistException getFaultInfo() {
        return this.compteTypeNotExistException;
    }
}
