package alom.bank.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.402+02:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "GestionBankImplService",
                  wsdlLocation = "http://localhost:8080/cxf-bank-server/GestionBank?wsdl",
                  targetNamespace = "http://front.server.bank.alom/")
public class GestionBankImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://front.server.bank.alom/", "GestionBankImplService");
    public final static QName GestionBankImplPort = new QName("http://front.server.bank.alom/", "GestionBankImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf-bank-server/GestionBank?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionBankImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf-bank-server/GestionBank?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionBankImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionBankImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionBankImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionBankImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionBankImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionBankImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GestionBank
     */
    @WebEndpoint(name = "GestionBankImplPort")
    public GestionBank getGestionBankImplPort() {
        return super.getPort(GestionBankImplPort, GestionBank.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionBank
     */
    @WebEndpoint(name = "GestionBankImplPort")
    public GestionBank getGestionBankImplPort(WebServiceFeature... features) {
        return super.getPort(GestionBankImplPort, GestionBank.class, features);
    }

}
