
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.329+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "IncorrectValueException", targetNamespace = "http://front.server.bank.alom/")
public class IncorrectValueException_Exception extends Exception {

    private alom.bank.client.IncorrectValueException incorrectValueException;

    public IncorrectValueException_Exception() {
        super();
    }

    public IncorrectValueException_Exception(String message) {
        super(message);
    }

    public IncorrectValueException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IncorrectValueException_Exception(String message, alom.bank.client.IncorrectValueException incorrectValueException) {
        super(message);
        this.incorrectValueException = incorrectValueException;
    }

    public IncorrectValueException_Exception(String message, alom.bank.client.IncorrectValueException incorrectValueException, java.lang.Throwable cause) {
        super(message, cause);
        this.incorrectValueException = incorrectValueException;
    }

    public alom.bank.client.IncorrectValueException getFaultInfo() {
        return this.incorrectValueException;
    }
}
