
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-08T17:08:06.355+02:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "IncorrectCompteOwnerException", targetNamespace = "http://front.server.bank.alom/")
public class IncorrectCompteOwnerException_Exception extends Exception {

    private alom.bank.client.IncorrectCompteOwnerException incorrectCompteOwnerException;

    public IncorrectCompteOwnerException_Exception() {
        super();
    }

    public IncorrectCompteOwnerException_Exception(String message) {
        super(message);
    }

    public IncorrectCompteOwnerException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IncorrectCompteOwnerException_Exception(String message, alom.bank.client.IncorrectCompteOwnerException incorrectCompteOwnerException) {
        super(message);
        this.incorrectCompteOwnerException = incorrectCompteOwnerException;
    }

    public IncorrectCompteOwnerException_Exception(String message, alom.bank.client.IncorrectCompteOwnerException incorrectCompteOwnerException, java.lang.Throwable cause) {
        super(message, cause);
        this.incorrectCompteOwnerException = incorrectCompteOwnerException;
    }

    public alom.bank.client.IncorrectCompteOwnerException getFaultInfo() {
        return this.incorrectCompteOwnerException;
    }
}
